config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 1000 }
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name, presence: true, length: {minimum:3, maximum:25}
  validates_uniqueness_of :name
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_many :articles, dependent: :destroy
  validates :username, presence: true, 
                      uniqueness: { case_sensitive: false }, 
                      length: { minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, 
                      uniqueness: { case_sensitive: false }, 
                      length: { maximum: 105 },
                      format: { with: VALID_EMAIL_REGEX }
  has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  
  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:alert] = "You must be logged in to perform that action"
      redirect_to login_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @articles = Article.order("created_at DESC").paginate(page: params[:page], per_page: 5)
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:notice] = "Article was ceated succesfully"
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article was updated succesfully"
      redirect_to @article
    else
      render 'edit'
    end
  end

  def show
  end

  def destroy
    @article.destroy
    redirect_to articles_path
    flash[:notice] = "Article deleted succesfully" 
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, category_ids: [])
  end

  def require_same_user
    if current_user != @article.user and !current_user.admin?
      flash[:alert] = "You can only edit or delete your own articles"
      redirect_to @article
    end
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :require_admin, except: [:show]

  def index
    @categories = Category.order("name ASC").all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save 
      flash[:notice] = "Category is succesfully created"
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def update
    if @category.update(category_params)
      flash[:notice] = "Category was updated succesfully"
      redirect_to @category
    else
      render 'edit'
    end
  end

  def show
    @category_articles = @category.articles.paginate(page: params[:page], per_page: 5)
  end

  def destroy
    @category.destroy
    redirect_to categories_path
    flash[:notice] = "Category deleted succesfully" 
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def set_category
    @category = Category.find(params[:id])
  end

  def require_admin
    if !logged_in? || (logged_in? and !current_user.admin?)
      flash[:danger] = "only admins can perform that action"
      redirect_to root_path
    end

  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to articles_path if logged_in?
  end
  
  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Welcome #{user.username}"
      redirect_to user
    else
      flash.now[:alert] = "there was someting wrong with your login details"
      render 'new' 
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "logged out"
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:edit, :update]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def show 
    @user_articles = @user.articles.order("created_at DESC").paginate(page: params[:page], per_page: 5)
  end

  def index
    @users = User.order("created_at ASC").paginate(page: params[:page], per_page: 20)
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(users_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Hi #{ @user.username }, welcome to the ALPHA-BLOG, you have been usccesfully signed up"
      redirect_to articles_path
    else
      render 'new'
    end
  end

  def update
    if @user.update(users_params)
      flash[:notice] = "Your account is updated succesfully"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil if @user == current_user
    flash[:notice] = "Account and all associated articles successfully deleted"
    redirect_to root_path
  end

  private

  def users_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user and !current_user.admin?
      flash[:alert] = "#{current_user.name} can not edit #{@user.name}"
      redirect_to @user
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  include ArticleHelper

  def gravatar_for(user, options = { size: 80 })
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    image_src = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(image_src, alt: user.username, class: "rounded shadow")
  end
  
  def gravatar_card(user, options = { size: 80 })
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    image_src = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(image_src, alt: user.username, class: "rounded mx-auto d-block")
  end

end

app/helpers/article_helper.rb
module ArticleHelper
  def LastUpdated(article)
    if article.updated_at != article.created_at
      # "<small>Created <%= time_ago_in_words(article.updated_at) %> ago, edited <%= time_ago_in_words(article.created_at) %> ago</small>"
      "Created #{time_ago_in_words(article.created_at)} ago, edited #{time_ago_in_words(article.updated_at)}"
    else
      # "<small>Created <%= time_ago_in_words(article.updated_at) %> ago</small>"
      "Created #{time_ago_in_words(article.created_at)} ago"
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
  <div class="row justify-content-md-center">
    <div class="col-8 mb-4">
      <div class="card shadow text-center">
        <div class="card-header">
            by <%= link_to article.user.username, user_path(article.user) %>
        </div>
        <div class="card-body">
          <h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-success" %></h5>
          <p class="card-text"><%= truncate(article.description, length: 100) %></p>
          <%= link_to 'View', article_path(article), class: "btn btn-outline-success" %>
          <% if logged_in? && (article.user == current_user || current_user.admin?) %>
            <%= link_to 'Edit', edit_article_path(article), class: "btn btn-outline-info" %>
            <%= link_to 'Delete', article_path(article), method: :delete, data: { confirm: "Are you sure?"}, class: "btn btn-outline-danger" %>
          <% end %>
        </div>
        <div class="card-footer text-muted">
          <small><%= LastUpdated(article) %></small>
          <% if article.categories.any? %>
            <div class="m-2">
              Categories:
              <% article.categories.each do |category| %>
                <%= link_to category.name, category_path(category), class: "btn btn-outline-dark btn-sm m-1" %>
              <% end %>
            </div>
          <% end %>
          </div>
      </div>
    </div>
  </div>
<% end %>

app/views/articles/_form.html.erb
<%= form_with(model: @article, class: "shadow p-3 mb-2 bg-dark rounded", local: true) do |f| %>
  <div class="form-group row">
    <%= f.label :title, class: "col-2 col-form-label text-white" %>
    <div class="col-10">
      <%= f.text_field :title, class: "form-control shadow", placeholder: "Title of blogpost" %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :description, class: "col-2 col-form-label text-white" %>
    <div class="col-10">
      <%= f.text_area :description, rows: 10, class: "form-control shadow", placeholder: "description of blogpost" %>
    </div>
  </div>
  <div class="form-group">
    <div class="row">
      <div class="col-2 col-form-label text-white">
        <p>Category:</P>
      </div>
      <div class="col-10 mb-2">
        <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
          <% cb.label(class: "checkbox-inline input_checkbox text-white") {cb.check_box(class: "checkbox mr-1 ml-3") + cb.text} %>
        <% end %>
      </div>
    </div> 
    <div class="form-group row justify-content-md-center">
      <%= f.submit class: "btn btn-outline-light btn-white col-4" %>
    </div>
  </div>
<% end %>

app/views/articles/edit.html.erb
<div class="row justify-content-md-center mb-2">
  <div class="text-center">
    <h1>Edit article: <%= @article.title %></h1>
    </div>
</div>
<div class="row justify-content-md-center">
  <div class="col-8">
    <%= render 'shared/errors', obj: @article %>
    <%= render 'form' %>
  </div>
</div>
<div class="row justify-content-md-center mt-4">
  <%= link_to 'Return to artilce listing', articles_path, class: "btn btn-info col-4" %>
</div>

app/views/articles/index.html.erb
<div class="row justify-content-md-center mb-2">
  <div class="text-center">
    <h1>Listing all articles</h1>
  </div>
</div>
<% if logged_in? %>
  <div class="row justify-content-md-center">
    <div class="text-center">
      <%= link_to 'Add article', new_article_path, class: "btn btn-primary" %>
    </div>
  </div>
<% end %>
<div class="d-flex justify-content-center apple_pagination">
  <%= will_paginate @articles %>
</div>
<%= render 'article', obj: @articles %>
<div class="d-flex justify-content-center apple_pagination">
  <%= will_paginate @articles %>
</div>

app/views/articles/new.html.erb
<div class="row justify-content-md-center mb-2">
  <div class="text-center">
    <h1>Create a new article</h1>
  </div>
</div>
<div class="row justify-content-md-center">
  <div class="col-8">
    <%= render 'shared/errors', obj: @article %>
    <%= render 'form' %>
  </div>
</div>
<div class="row justify-content-md-center mt-4">
  <%= link_to 'Return to artilce listing', articles_path, class: "btn btn-info col-4" %>
</div>

app/views/articles/show.html.erb
<div class="row justify-content-md-center mb-2">
  <div class="text-center">
    <h1> <%= @article.title %></h1>
  </div>
</div>
<% if logged_in? && (@article.user == current_user || current_user.admin?) %>
  <div class="row justify-content-md-center mb-2">
    <div class="text-center">
      <%= link_to 'Edit article', edit_article_path, class: "btn btn-info" %>
      <%= link_to 'Delete article', article_path, method: :delete, data: { confirm: "Are you sure?"}, class: "btn btn-outline-danger" %>
    </div>
  </div>
<% end %>
<div class="row justify-content-md-center">
  <div class="col-8">
    <div class="card shadow my-2">
      <div class="card-header text-center">
          by <%= link_to @article.user.username, user_path(@article.user) %>
      </div>
      <div class="card-body">
        <div class="card-text"><%= simple_format(@article.description) %></div>
      </div>
      <div class="card-footer text-muted text-center">
        <small><%= LastUpdated(@article) %></small>
        <% if @article.categories.any? %>
          <div class="m-2">
            Categories:
            <% @article.categories.each do |category| %>
              <%= link_to category.name, category_path(category), class: "btn btn-outline-dark btn-sm m-1" %>
            <% end %>
          </div>
        <% end %>
        <%= link_to gravatar_for(@article.user, size:60) , user_path(@article.user) %>
      </div>
    </div>
  </div>
</div>
<div class="row justify-content-md-center mt-4">
  <%= link_to 'Return to artilce listing', articles_path, class: "btn btn-info col-4" %>
</div>

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class: "btn btn-outline-dark m-1" %>

app/views/categories/_form.html.erb
<%= form_with(model: @category, class: "shadow p-3 mb-2 bg-dark rounded", local: true) do |f| %>
  <div class="form-group row">
    <%= f.label :name, class: "col-2 col-form-label text-white" %>
    <div class="col-10">
      <%= f.text_field :name, class: "form-control shadow", placeholder: "Enter name of category" %>
    </div>
  </div>
  <div class="form-group row justify-content-md-center">
    <%= f.submit(@category.new_record? ? "Add category" : "Update category", class: "btn btn-outline-light btn-white col-4") %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div class="row justify-content-md-center mb-4">
  <div class="text-center">
    <h1>Edit <%= @category.name %></h1>
  </div>
</div>
<div class="row justify-content-md-center">
  <div class="col-8">
    <%= render 'shared/errors', obj: @category %>
    <%= render 'form' %>
  </div>
</div>
<div class="row justify-content-md-center mt-4">
  <%= link_to 'Return to category listing', categories_path, class: "btn btn-info col-4" %>
</div>

app/views/categories/index.html.erb
<div class="row justify-content-md-center mb-2">
  <div class="text-center">
    <h1>Categories:</h1>
  </div>
</div>
<% if logged_in? && current_user.admin? %>
  <div class="row justify-content-md-center">
    <div class="text-center">
      <%= link_to 'Add category', new_category_path, class: "btn btn-primary" %>
    </div>
  </div>
<% end %>
<table class="table my-4">
  <thead>
    <tr>
      <th scope="col">Category</th>
      <th scope="col">Articles</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= pluralize(category.articles.count, "category") %></td>
        <td>
          <%= link_to 'View', category_path(category), class: "btn btn-outline-success" %>
          <%= link_to 'Edit', edit_category_path(category), class: "btn btn-outline-info" %>
          <%= link_to "Delete", category_path(category), class: "btn btn-outline-danger", method: :delete, data: { confirm: "Are you sure?"} %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/categories/new.html.erb
<div class="row justify-content-md-center mb-4">
  <div class="text-center">
    <h1>New category</h1>
  </div>
</div>
<div class="row justify-content-md-center">
  <div class="col-8">
    <%= render 'shared/errors', obj: @category %>
    <%= render 'form' %>
  </div>
</div>
<div class="row justify-content-md-center mt-4">
  <%= link_to 'Return to category listing', categories_path, class: "btn btn-info col-4" %>
</div>

app/views/categories/show.html.erb
<div class="row justify-content-md-center mb-2">
  <div class="text-center">
    <h1>Category: <%= @category.name %></h1>
  </div>
</div>
<% if logged_in? and current_user.admin? %>
  <div class="row justify-content-md-center">
    <div class="text-center">
      <%= link_to 'Edit category', edit_category_path, class: "btn btn-info" %>
      <%= link_to 'Delete category', category_path, method: :delete, data: { confirm: "Are you sure?"}, class: "btn btn-outline-danger" %>
    </div>
  </div>
<% end %>
<div class="d-flex justify-content-center apple_pagination">
  <%= will_paginate @category_articles %>
</div>
<% if @category_articles.count != 0 %>
  <%= render 'articles/article', obj: @category_articles %>
<% else %>
  <div class="row justify-content-md-center">
    <div class="col-8 mb-4">
      <div class="card shadow text-center">
        <div class="card-header">
           This can be your article
        </div>
        <div class="card-body">
          <h5 class="card-title">Empty category</h5>
          <p class="card-text">There are no articles in the category <%= @category.name %>. You can be the first to write an article for this category!</p>
          <%= link_to 'Write Article', new_article_path, class: "btn btn-primary" %>
        </div>
        <div class="card-footer text-muted">
          <small>Anytime is a good time to start writing</small>
        </div>
      </div>
    </div>
  </div>
<% end %>
<div class="d-flex justify-content-center apple_pagination">
  <%= will_paginate @category_articles %>
</div>
<div class="row justify-content-md-center mt-4">
  <%= link_to 'Return to category listing', categories_path, class: "btn btn-info col-4" %>
</div>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white">
  <div class="container text-center">
    <small>Copyright &copy; <%= link_to "Mike Cinjee", "https://cinj.nl", class: "text-white" %></small>
  </div>
</footer>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <%= link_to "ALPHA BLOG", root_path, class: "nav-bar-brand mr-3", id: "logo" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to "Articles", articles_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "About", about_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "bloggers", users_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown mr-2">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Categories</a>
          <div class="dropdown-menu text-dark" aria-labelledby="navbarDropdown"> 
            <% Category.all.each do |category| %>
              <%= link_to "#{category.name}", category_path(category), class: "dropdown-item" %>
            <% end %>
            <% if logged_in? and current_user.admin? %>
              <div class="dropdown-divider"></div>
              <%= link_to "Manage Categories", categories_path, class: "dropdown-item" %>
              <%= link_to "Create New Category", new_category_path, class: "dropdown-item" %>
            <% end %>
          </div>
        </li>
        <% if logged_in? %>
          <li class="nav-item">
            <%= link_to "Write Article", new_article_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
      <div class="form-inline my-4 my-lg-0">
        <ul class="navbar-nav">
          <% if logged_in? %>
            <li class="nav-item dropdown mr-2">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%= current_user.username %>
              </a>
              <div class="dropdown-menu text-dark" aria-labelledby="navbarDropdown"> 
                <%= link_to "Show profile", user_path(current_user), class: "dropdown-item" %>
                <%= link_to "Edit profile", edit_user_path(current_user), class: "dropdown-item" %>
                <%= link_to "Delete profile", user_path(current_user), class: "dropdown-item", method: :delete, data: { confirm: "Are you sure?"} %>
              </div>
            </li>
            <li class="nav-item">
              <%= link_to "Log out", logout_path, class: "nav-link btn btn-outline-light", method: :delete %>
            </li>
          <% else %>
            <li class="nav-item mr-2">
              <%= link_to "Log in", login_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Sign up!", signup_path, class: "nav-link btn btn-outline-light" %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    <%= render 'layouts/navigation' %>
    <div class="container py-4">
      <%= render 'shared/messages' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="row justify-content-md-center mb-2">
  <div class="text-center">
    <h1 class="text-center">About me!</h1>
  </div>
</div>
<div class="row justify-content-md-center">
  <div class="col-8">
    <div class="card shadow text-center mb-2">
      <div class="card-header">
        By Mike Cinjee
      </div>
      <div class="card-body">
        <div class="card-text text-left">
          <p>Blog, build for The Complete Ruby on Rails Developer Course on <strong>Udemy</strong>!</p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="jumbotron text-center text-white font-weight-bold m-auto">
  <h1 class="display-4 text-white"><span class="bg-dark py-1 px-3 rounded">Alpha Blog</span></h1>
  <p class="lead font-weight-bold mt-5"><span class="bg-dark py-1 px-3 rounded">This is a blog created in Rails for the <strong>Udemy</strong> course The Ultimate Rails Course!</span></p>
  <hr class="my-4">
  <p><span class="bg-dark py-1 px-3 rounded">Please look around and write and article if you like!</span></p>
  <%= link_to  "Sign up!", signup_path, class: "btn btn-success btn-lg" %>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger alert-dismisable fade show" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <p class="alert-heading"><strong>ERROR:</strong> The following erros prevented the <%= obj.class.name.downcase %> to be <%= obj.new_record? ? "saved:" : "updated:" %></p>
    <ul class="errors">
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="row justify-content-md-center mb-2">
  <div class="text-center">
    <h1>Edit user: <%= @user.username %></h1>
  </div>
</div>
<div class="row justify-content-md-center">
  <div class="col-8">
    <%= render 'shared/errors', obj: @user %>
    <%= render 'form' %>
  </div>
</div>
<div class="row justify-content-md-center mt-4">
  <%= link_to 'Return to Users', users_path, class: "btn btn-info col-4" %>
</div>

app/views/users/index.html.erb
<div class="row justify-content-md-center mb-4">
  <div class="col-10">
    <h1 class="text-center">Alpha Bloggers</h1>
  </div>
</div>
<table class="table">
  <thead>
    <tr>
      <th scope="col"></th>
      <th scope="col">Username</th>
      <th scope="col">Articles</th>
      <th scope="col">Joined</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <th scope="row"><%= gravatar_card user, size:50 %></th>
        <td><%= user.username %></td>
        <td><%= pluralize(user.articles.count, "article") %></td>
        <td><small><%= time_ago_in_words(user.created_at)%> ago</small></td>
        <td>
          <%= link_to 'View', user_path(user), class: "btn btn-outline-success" %>
          <% if logged_in? && (user == current_user || current_user.admin?) %>
            <%= link_to 'Edit', edit_user_path(user), class: "btn btn-outline-info" %>
            <%= link_to "Delete", user_path(user), class: "btn btn-outline-danger", method: :delete, data: { confirm: "Are you sure?"} %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="d-flex justify-content-center apple_pagination">
  <%= will_paginate @users %>
</div>

app/views/users/new.html.erb
<div class="row justify-content-md-center mb-4">
  <div class="text-center">
    <h1>Register user</h1>
  </div>
</div>
<div class="row justify-content-md-center">
  <div class="col-8">
    <%= render 'shared/errors', obj: @user %>
    <%= render 'form' %>
  </div>
</div>
<div class="row justify-content-md-center mt-4">
  <%= link_to 'Return to Users', users_path, class: "btn btn-info col-4" %>
</div>

app/views/users/show.html.erb
<div class="row justify-content-md-center mb-2">
  <div class="text-center">
    <%= gravatar_for @user, size:150 %>
    <h1 class="m-2"><%= @user.username %>'s profile</h1>
  </div>
</div>
<% if logged_in? && (@user == current_user || current_user.admin?) %>
  <div class="row justify-content-md-center">
    <div class="text-center">
      <%= link_to "Edit your profile", edit_user_path(@user), class: "btn btn-outline-info mt-2" %>
      <%= link_to "Delete profile", user_path(@user), class: "btn btn-outline-danger mt-2", method: :delete, data: { confirm: "Are you sure? Account and all associated articles will be deleted"} %>
    </div>
  </div>
<% end %>
<div class="row justify-content-md-center">
  <div class="col-8">
    <%= render 'shared/errors', obj: @user %>
    <h3 class="text-center">Articles</h3>
  </div>
</div>
<div class="d-flex justify-content-center apple_pagination">
  <%= will_paginate @user_articles %>
</div>
<% if @user_articles.count != 0 %>
  <%= render 'articles/article', obj: @user_articles %>
<% else %>
  <div class="row justify-content-md-center">
    <div class="col-8 mb-4">
      <div class="card shadow text-center">
        <div class="card-header">
           <%= @user.username %> has no articles
        </div>
        <div class="card-body">
          <h5 class="card-title">No articles written</h5>
          <p class="card-text"><%= @user.username %> has not written an article yet. Don't be afraid. You can write an article to show it is easy to do!</p>
          <%= link_to 'Write Article', new_article_path, class: "btn btn-primary" %>
        </div>
        <div class="card-footer text-muted">
          <small>Anytime is a good time to start writing</small>
        </div>
      </div>
    </div>
  </div>
<% end %>
<div class="d-flex justify-content-center apple_pagination">
  <%= will_paginate @user_articles %>
</div>